rel:
	@cd hifb;   make
	@cd vio;    make
	@cd venc;   make
	@cd region; make
	@cd audio;  make
	@cd tde;    make
	@cd ive;    make
	@cd fisheye;    make
	@cd dis;    make
	@cd pciv;    make slave
	@cd scene_auto;    make
	@cd snap;   make

clean:
	@cd hifb;   make clean
	@cd vio;    make clean
	@cd venc;   make clean
	@cd region; make clean
	@cd audio;  make clean
	@cd tde;    make clean
	@cd ive;    make clean
	@cd fisheye;    make clean
	@cd dis;    make clean
	@cd pciv;    make clean
	@cd scene_auto;    make clean
	@cd snap;   make clean

cleanall:
	@cd hifb;   make clean;   make cleanstream
	@cd vio;    make clean;   make cleanstream
	@cd venc;   make clean;   make cleanstream
	@cd region; make clean;   make cleanstream
	@cd audio;  make clean;   make cleanstream
	@cd tde;    make clean
	@cd ive;    make clean
	@cd fisheye;    make clean
	@cd dis;    make clean
	@cd pciv;    make clean;  make cleanstream
	@cd scene_auto;    make clean
	@cd snap;   make clean;   make cleanstream
